language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules

before_script:
  - npm install -g firebase-tools

script:
  - unset CI
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  
branches:
  only:
    - "master"
    


