language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
script:
- npm install
- npm run test
- unset CI
- npm run build
deploy:
  provider: firebase
  token:
    secure: YOUR ENCRYPTED token
  cleanup: true
  local_dir: build
  on:
    branch: master
env:
  global:
  - secure: fNiCGG/PX2ZfzhBkciv+SdGWVIwXz5UGk1tP8N5BuLeagnYseQEa0ytbFQ+lETsTzqG2fF3vCvfgHKjPQf3v3n+S4mRbifUkBa9pM5rdaym5JcDmyUJKbTAAN3NkihHS/He80oNICV+5uefEmT1OVD58JfzDvZPRyKeIWwC6etUHnrhZgnXvjUagtNIV8JqokN57jqu4uEoGyJ/7Bfs42V9necfczAN95G30TdSZ2rRjTK5/ItbqOGF9n6Qjs5hAzKKgo7M+mCeFOaX6TLIACN/aTFBMBWwwhX1b2WajVNbXev8aGwVA2rkOw2zDiN4xJ96Ygo9sLIp6MpUPZskRJi/NQ8QEuqLyj6Spmb3WaNNhpikmRSiwDRxHtJ/YGD46MYKB+46U9l2gDLBDMuk3BFCcZqm9V8pttIEe0P5ZL7J/bSJ2FGpdMKllcKpYTsEBZOxA93zCIMHShfMStHBCObcv0lu4bdW4We0teWSvbvXea3XUOGHKnHBHZICV8KmfdSGNwYlAmMsKLx1NwSDumO1IMbfJ3NhifInvc8nyusyMh78FjPAU3bG9MyJjtiLPhJML8EN4mVtFppyvUJDaWzyXbKvzyA9uFckyR3ftsi6BnN062TSBd79m8NTMaUzQjICZID4PKldrSS4CPxfn0PE8ix0RO6UZgk6e5eLAsnc=
  - secure: Dxo6tl9oRcTW18kfrZF3N5FEeY6Wd1xbA08RqMHZvQx20jQvLp9TkNMEqH7S3yzq5oGaMZf1HxLKMMWJ1B9vl4qSvbX24PJMkKs5ktSvTG39GUvy6MXtDPLOf63/ASs1I5qtgo1IwojXOPYvxVSqBmYn18atXpfs3G1nA09A1C6hVdDskCUve6Ujm+9Q+/b++bMM3nhN3+HGGYvYUBcnrGTuydbRbdra4jnu5kFGKFkxqmW7a7huLgSeiL6LI2au9S8VJeG+J1TvK7NF1jEaA+q9mKGfuplb9FDVilMm8/6ApOvl7aujxTBlpDWaczTnNCTNmOuLJy9yvmazD7DmCw/x0Rrs3AajioBEE+7dwRM7818n72XVtkKiKac0YQlqJ+GOGt+5uF6FC4zJm/1U8INK3cJmQ119MQGuT6DYi3A1RFb6e0DdPsUZqLfrqnh+bE3ZJyYC4fuMRrxjOXSx82Faj51JTfSyGN3ZiHp3O7Wu5osVLDwHnYkwA1DpJx7nqgbKVtNVXLE6LiM6HrVUsUUWK2Ms7vpGhWkfHr9oaSf96u9LsDxKHJyoQrE4n85fZTN7Wbrx4alaQ7gJdtiAhGHoAV98T4YHnbjzLeNMq95CNXgwDG5emEmTcpRs3LE04xJIzYgXPRzd2PsnEYHmhDi0C2SnRQAyxK2QYDsmKH0=
  - secure: BDgZwfD88uSH75U6ek5rBdrKLm9WXCTul1oJzKmSY8hclMIyMTMpaRpDpwgu+AGVZyJB3MWO47c6tFwkbyYitAKXJQUcMc3xc7FCqSek1FHq56IwViEVrMOAVfqfDQPe3G8/Fxaj2pRLBs84ecOHt6nUPJJ2c5Oaor/ilqftxIjqQWQu7ixlrw+RDE7HJVCLycq0FPy1qMc1iRD0XkX61qg35LqadcCyDIZvJVWFoG+hW/0gJnbCOSK4LGfsj+l4BOUPeqAe0vcsFmLpE6RAYHowBsx1eP4hbziYSMO63f6PLgjZIyLqKQbbJItMA5hg65byt81dW8HSsIhG+a9E7TovwoGOBGwWWhvI/dZ7I4WakvOI1lWCaRJMbRB/tk84zKkkHB0Gvp2LrX49aKBRkPe/8EhtcFFNkUiiXDAr1u+GGdsq+0+nT6DsvNpu2lZx9cWYFHWbSN1IZHSt+/PFTz4IlQxXX+NPbsF3+LSWdm+aALcD/aI955XoLB+MG5lk7mz+5ChTmWwunoEeCSKFcuOxFn64o5+6SUKiM76TsWp6sNIioWsUOnSl5+35iRHowAF0Y9ccMe1zb5y8zjFz9ZW1lqYNPdd9R1JcV0FMC3SVnMqr/G5x2HWJgvNrtN5B2DYFW9ODdpOF+Y6rXuerAXtlaeTi9NVwu04eRwCSxUM=
