language: node_js

node_js:
- 'lts/*'

cache:
    directories:
      - node_modules
script:
  - unset CI
  - npm install
  - npm run tests
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
