language: node_js

node_js:
- 'lts/*'

cache: yarn
jobs:
    include:
        - stage: test
          script:
            - echo 'Deploy!!'
            - echo 'Installing Deps!'
            - yarn
            - echo 'Testing!'
            - yarn test
        - stage: deploy
          script:
            - npm install gh-pages
            - npm run build
            - npm run deploy
